---

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: install apache and php
      package: 
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes

