---

- hosts: all
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: install updates (Rocky Linux)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      changed_when: false
      when: ansible_facts["distribution"] == "Rocky"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: false
      when: ansible_facts["distribution"] == "Ubuntu"
      
- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers



 




